---
title: "Regression HW3"
author: "Pooria Assarehha"
date: "2023-11-22"
output: pdf_document
---

## Ex 3

```{r, fig.height=7, fig.width=11}
x = c(25, 35, 60, 45, 50, 37.5, 30,
      55, 60, 22.5, 65, 50, 20, 15,
      27.5, 55, 40, 45, 17.5)
y = c(37.4, 57.7, 337.6, 142.5, 182.4, 67.5, 37.5,
      225.0, 258.1, 25.0, 297.4, 170.0, 20.0, 13.5,
      40.8, 207.8, 105.5, 132.6, 19.1)

par(
  mfrow=c(2,2)
  )

################################### a ##########################################

plot(
  y~x, 
  main = "Car Crash Data",
  xlab = "Vehicle speed",
  ylab = "Brake distance"
)

################################### b ##########################################

model = lm(y~x)
ri = model$residuals
rstd = (ri - mean(ri))/sd(ri)
print("Residuals of the model")
print(rstd)

################################### c ##########################################

plot(
  rstd, 
  main = "Residuals of the model",
  ylab = bquote(e[i]),
  xlab = "Index (i)"
)


################################### d ##########################################

ystar = sqrt(y)

plot(
  ystar~x, 
  main = "Car Crash ",
  xlab = "Vehicle speed",
  ylab = "Log of Brake distance"
)

model2 = lm(ystar~x)

ri_star = model2$residuals
rstar_std = (ri_star - mean(ri_star))/sd(ri_star)

print("Residuals of the Logged model")
print(rstar_std)

plot(
  rstar_std, 
  main = "Residuals of the Logged model",
  ylab = bquote(e[i]),
  xlab = "Index (i)"
)

################################### e ##########################################

print(paste("R-squared of the normal model", summary(model)$r.squared))
print(paste("R-squared of the logged model", summary(model2)$r.squared))

```

## Ex 4

```{r}
p = c(8599, 8600, 9048, 9048, 9484, 9487, 9487, 9936, 9938, 10377, 10379,
      6380, 6818, 6817, 6818, 7266, 7268, 7709, 7710, 8156, 8158, 8597,
      4599, 4600, 5044, 5043, 5044, 5488, 5487, 5931, 5932, 5932, 6380)
v = c(3789, 3789, 3979, 3979, 4167, 4168, 4168, 4358, 4358, 4546, 4547,
      2842, 3030, 3031, 3031, 3221, 3221, 3409, 3410, 3600, 3600, 3788,
      2084, 2084, 2273, 2273, 2273, 2463, 2463, 2651, 2652, 2652, 2842)

pvnrt = lm(p~v)
print("Residuals")
ri = pvnrt$residuals
print(ri)

```

```{r, fig.height=15, fig.width=10}
par(mfrow= c(4,1))
plot(pvnrt, which=c(1,2))
rstd = (ri - mean(ri))/sd(ri)
plot(
  rstd,
  pvnrt$fitted.values,
  main="Studentized Residuals vs Fitted",
  xlab="Fitted Values",
  ylab = "Studentized Residuals"
)

plot(
  rstd,
  main="Studentized Residuals vs Time",
  xlab="Time Index",
  ylab = "Studentized Residuals"
)

```

## Ex 5

```{r}
anova(pvnrt)
```

```{r}
v.factor = factor(v)
pvnrt.f = lm(p~v.factor)
anova(pvnrt.f)
```

```{r}
ss.e = anova(pvnrt)[2,2]
ss.pe = anova(pvnrt.f)[2,2]
ss.lf = ss.e - ss.pe
df.e = anova(pvnrt)[2,1]
df.pe = anova(pvnrt.f)[2,1]
df.lf = df.e - df.pe
ms.lf = ss.lf/df.lf
ms.pe = ss.pe/df.pe
FO = ms.lf/ms.pe
pvalue = 1-pf(FO, df.lf, df.pe)
pvalue
```

REJECT $H_0$

## Ex 8

$$
x_A = x_B + 2 \ \Rightarrow \ \hat{ln(y_B)} - \hat{ln(y_B)} = 0.04\times 2 \ \Rightarrow \ \hat{ln(\frac{y_A}{y_B})} = 0.08 \Rightarrow \frac{y_A}{y_B} = e^{0.08}
$$

## Ex 9

$$
\begin{cases} \bar{y}_1 = 5 \\ \bar{y}_2 = 10 \\ \bar{y}_3 = 10.\bar{6} \\ \bar{y}_4 = 20 
\end{cases} \quad , \quad SSPE = \sum_{i=1}^4 \sum_{j=1}^3 (y_{ij} - \bar{y}_{i\cdot})^2 
$$

$$
SSPE = (1^2 + 1^2 + 0) + (1^2 + 1^2 + 0) + (8.\bar{6}^2 + 2.\bar{3}^2 + 5.\bar{3}^2) + (2^2 + 2^2 + 0) = 132.\bar{6}
$$

```{r}
x = rep(c(0,5,10,15), rep(3,4))
y = c(4, 5, 6, 11, 9, 10, 17, 13, 2, 18, 22, 20)

lm.1 = lm(y~x)
lm.2 = lm(y~factor(x))

ss.e = anova(lm.1)[2,2]
ss.pe = anova(lm.2)[2,2]
ss.lf = ss.e - ss.pe
df.e = anova(lm.1)[2,1]
df.pe = anova(lm.2)[2,1]
df.lf = df.e - df.pe
ms.lf = ss.lf/df.lf
ms.pe = ss.pe/df.pe
FO = ms.lf/ms.pe
pvalue = 1-pf(FO, df.lf, df.pe)
pvalue
```

Don't Reject $H_0$
